# Generated by Django 6.0.7 on 2026-08-01 01:30

import django.contrib.gis.db.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
                ('area_km2', models.FloatField(blank=True, null=True)),
                ('flood_risk', models.CharField(blank=True, choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High')], max_length=20, null=True)),
                ('mean_elevation_m', models.FloatField(blank=True, null=True)),
                ('water_coverage_percent', models.FloatField(blank=True, null=True)),
                ('population_exposed', models.IntegerField(blank=True, null=True)),
                ('water_bodies_intersecting', models.IntegerField(blank=True, null=True)),
                ('result_metadata', models.JSONField(blank=True, default=dict)),
                ('processing_status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETE', 'Complete'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
