# Generated by Django 6.0.7 on 2026-08-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysis',
            name='flood_risk',
            field=models.CharField(blank=True, choices=[('LOW', 'Low'), ('MODERATE', 'Moderate'), ('HIGH', 'High'), ('INSUFFICIENT_DATA', 'Insufficient Data')], max_length=20, null=True),
        ),
    ]
